module.exports = { word: 'happy',
  synonyms:
   [ 'contented',
     'content',
     'cheerful',
     'cheery',
     'merry',
     'joyful',
     'jovial',
     'jolly',
     'joking',
     'jocular',
     'gleeful',
     'carefree',
     'untroubled',
     'delighted',
     'smiling',
     'beaming',
     'grinning',
     'glowing',
     'satisfied',
     'gratified',
     'buoyant',
     'radiant',
     'sunny',
     'blithe',
     'joyous',
     'beatific',
     'blessed' ],
  antonyms: [ 'sad' ],
  examples: [ 'Melissa came in looking happy and excited' ] }