module.exports = [{
  "word": "happy",
  "synonyms": [{
    "id": "contented",
    "language": "en",
    "text": "contented"
  }, {
    "id": "content",
    "language": "en",
    "text": "content"
  }, {
    "id": "cheerful",
    "language": "en",
    "text": "cheerful"
  }, {
    "id": "cheery",
    "language": "en",
    "text": "cheery"
  }, {
    "id": "merry",
    "language": "en",
    "text": "merry"
  }, {
    "id": "joyful",
    "language": "en",
    "text": "joyful"
  }, {
    "id": "jovial",
    "language": "en",
    "text": "jovial"
  }, {
    "id": "jolly",
    "language": "en",
    "text": "jolly"
  }, {
    "id": "joking",
    "language": "en",
    "text": "joking"
  }, {
    "id": "jocular",
    "language": "en",
    "text": "jocular"
  }, {
    "id": "gleeful",
    "language": "en",
    "text": "gleeful"
  }, {
    "id": "carefree",
    "language": "en",
    "text": "carefree"
  }, {
    "id": "untroubled",
    "language": "en",
    "text": "untroubled"
  }, {
    "id": "delighted",
    "language": "en",
    "text": "delighted"
  }, {
    "id": "smiling",
    "language": "en",
    "text": "smiling"
  }, {
    "id": "beaming",
    "language": "en",
    "text": "beaming"
  }, {
    "id": "grinning",
    "language": "en",
    "text": "grinning"
  }, {
    "id": "glowing",
    "language": "en",
    "text": "glowing"
  }, {
    "id": "satisfied",
    "language": "en",
    "text": "satisfied"
  }, {
    "id": "gratified",
    "language": "en",
    "text": "gratified"
  }, {
    "id": "buoyant",
    "language": "en",
    "text": "buoyant"
  }, {
    "id": "radiant",
    "language": "en",
    "text": "radiant"
  }, {
    "id": "sunny",
    "language": "en",
    "text": "sunny"
  }, {
    "id": "blithe",
    "language": "en",
    "text": "blithe"
  }, {
    "id": "joyous",
    "language": "en",
    "text": "joyous"
  }, {
    "id": "beatific",
    "language": "en",
    "text": "beatific"
  }, {
    "id": "blessed",
    "language": "en",
    "text": "blessed"
  }],
  "antonyms": [{
    "id": "sad",
    "language": "en",
    "text": "sad"
  }],
  "examples": [{
    "text": "Melissa came in looking happy and excited"
  }]
}]